merge

diff --git a/auto_test b/auto_test
--- a/auto_test
+++ b/auto_test
@@ -34,6 +34,10 @@ cargo build --release
 # 初始化数组
 files_to_compare=()
 
+# 初始化计数器
+correct_count=0
+incorrect_count=0
+
 # 检查是否提供了单个 .sy 文件作为参数
 if [ "$#" -eq 1 ]; then
     sy_files=("$1")
@@ -51,6 +55,13 @@ for filename in "${sy_files[@]}"; do
         export base_name=$(basename "$filename" .sy)
         # 执行编译命令，输出到同一目录
         ./target/release/compiler "$filename" -o "$s_path/${base_name}.s" -a 2> /dev/null
+        compile_status=$?
+
+        if [ $compile_status -ne 0 ]; then
+            echo -e "$RED Failed to compile $filename $NC" 
+            ./target/release/compiler "$filename" -o "$s_path/${base_name}.s" 2>> "$o_path/${base_name}_compiler_error.log"
+            continue
+        fi
         
         # 使用 gcc 工具链把 .s 文件链接
         riscv64-linux-gnu-as "$s_path/${base_name}.s" -o "$o_path/${base_name}.o"
@@ -58,7 +69,7 @@ for filename in "${sy_files[@]}"; do
 
         # 检查 ELF 文件是否生成
         if [ ! -s "$elf_path/${base_name}.elf" ]; then
-            echo "Failed to generate ELF file: $elf_path/${base_name}.elf"
+            echo -e "$RED Failed to generate ELF file: $elf_path/${base_name}.elf $NC"
             exit 1
         fi
 
@@ -67,10 +78,10 @@ for filename in "${sy_files[@]}"; do
         timeout $timeout_duration bash -c '
         if [ -f "$in_path/${base_name}.in" ]; then
             qemu-riscv64-static "$elf_path/${base_name}.elf" < "$in_path/${base_name}.in" > "$ours_out_path/${base_name}.out" 2>&1 
-            echo "$?" >> "$ours_out_path/${base_name}.out"
+            echo -e "\n$?" >> "$ours_out_path/${base_name}.out"
         else
             qemu-riscv64-static "$elf_path/${base_name}.elf" > "$ours_out_path/${base_name}.out" 2>&1 
-            echo "$?" >> "$ours_out_path/${base_name}.out"
+            echo -e "\n$?" >> "$ours_out_path/${base_name}.out"
         fi
         # 删除.out文件的第一行 (时间记录)
         sed -i '1d' "$ours_out_path/${base_name}.out"
@@ -100,7 +111,14 @@ for files in "${files_to_compare[@]}"; do
     IFS=' ' read -r ours_file official_file <<< "$files"
     if diff -wB "$ours_file" "$official_file" > /dev/null; then
         echo -e "${GREEN}$(basename "$ours_file") 过了${NC}"
+        let correct_count++
     else
         echo -e "${RED}$(basename "$ours_file") 结果不一样!${NC}"
+        diff -wB "$ours_out_path/$(basename "$ours_file")" "$official_path/$(basename "$ours_file")" -y | head -n 10
+        let incorrect_count++
     fi
 done
+
+# 输出统计结果
+echo -e "${GREEN}通过的文件数: $correct_count${NC}"
+echo -e "${RED}未通过的文件数: $incorrect_count${NC}"
